In [2]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib qt

#### Regla de Oja

In [3]:
def oja(lr, x, w, v):
    '''
    lr: learning rate
    x: vector de entrada
    w: vector de pesos
    v: salida

    Devuelve deltaW, vector con la misma forma que w y x
    '''
    
    deltaW = lr*v*(x - v*w)
    return deltaW
    

#### Datos y parámetros

In [4]:
N = 4 #Dimension de la entrada
lr = 0.0005 #Learning rate

#Matriz de covarianza
c = np.ones(shape=(N, N), dtype=np.float32)

for i in range(N):
    c[i,i] = 2

#Su raíz cuadrada
c_sqrt = np.ones(shape=(N, N), dtype=np.float32)*0.309

for i in range(N):
    c_sqrt[i,i] = 1.309

print(c_sqrt)

[[1.309 0.309 0.309 0.309]
 [0.309 1.309 0.309 0.309]
 [0.309 0.309 1.309 0.309]
 [0.309 0.309 0.309 1.309]]


#### Inicializacion pesos

In [5]:
# seed=2                           
# np.random.seed(seed)

w = np.random.normal(loc=0, scale=0.1, size=(4,)) #Capa 2 afectada por capa 1

#### Verifico que el procedimiento indicado da entradas con la correlación deseada

In [6]:
K = 50000
z = np.zeros(shape=(K,N), dtype=np.float32)


for i in range(K):
    x = np.random.normal(loc=0, scale=1, size=(N,)) #Importante: varianza unitaria
    z[i,:] = np.dot(c_sqrt, x)

print("Valores medios")
print(np.mean(z, axis=0))

#Matriz de covarianza
c = np.zeros(shape=(N, N), dtype=np.float32)

for i in range(N):
    for j in range(N):
        c[i, j] = np.mean(z[:, i]* z[:, j], axis = 0)

print("Matriz de covarianza")      
print(c)

Valores medios
[0.0050936  0.00461623 0.00547546 0.00236551]
Matriz de covarianza
[[1.9996043  1.0116847  0.9935702  1.0045497 ]
 [1.0116847  2.007369   0.99794227 1.0104936 ]
 [0.9935702  0.99794227 1.9935169  0.99317455]
 [1.0045497  1.0104936  0.99317455 2.003756  ]]


#### Loop de aprendizaje

In [7]:
t = 50000 #Cantidad de entradas
wt = np.zeros(shape = (4,t))

for i in range(t):
    x = np.random.normal(loc=0, scale=1, size=(N,)) #Vector aleatorio  
    x_in  = np.dot(c_sqrt, x) #Entrada correlacionada
    v = np.dot(w, x_in) #Salida
    deltaW = oja(lr, x_in, w, v)
    w += deltaW
    wt[:,i] = w
    

In [8]:
for i in range(N):
    plt.plot(wt[i], label = "W_" + str(i+1))
plt.xlabel("Entrada")
plt.ylabel("Pesos")
plt.legend()
plt.show()

#### Autovalores y autovectores de C

In [9]:
values, vectors = np.linalg.eig(c)

print(values)
print(vectors)


[5.0068493 1.0081568 0.9915527 0.9976878]
[[-0.5003284  -0.24121091  0.61228615 -0.56266725]
 [-0.5025799  -0.25838047 -0.7742697  -0.2848849 ]
 [-0.49642333  0.8646689   0.00546358  0.07669258]
 [-0.5006484  -0.35693774  0.15994456  0.77224636]]
